version: '2'

services:
  tutorial-db:
    build: .
    container_name: pgroonga_container
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  db-store: